export const giphy = {
    bulbasaur: "https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExYWcxdTZtbDdlMmM0aWgwcnB1MzZ1bzlscDJ5OW00b3c5eGdrbWRmMSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/HH2bb3Pjq5IB2/giphy.gif",
    ivysaur: "https://media1.tenor.com/m/fYpoQ2t5lmkAAAAC/pokemon-ivysaur.gif",
    caterpie: "https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExaTB3cWs2NTBpZzQzb2Z0YzJwMW02Nzg2NXExMWprb290bDBndDM5aiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/4Vzo30iW56hBLyEDrH/giphy.gif",
    weedle: "https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExeHlmYndmbjExaDIwanM5cTR3ZGt5bDhmeG11YnI1ZjhxOGVzZmxmMiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/YzTM6OdRvimr1DSWc2/giphy.gif",
    venusaur: "https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExOG01dTRhenk1NDBzOGw1eXJtcXljZWw4YmFhc24yNDA2bDNrczBqYiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/EJOdcxm52IWNq/giphy.gif",
    charmeleon: "https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExZTRsanV0emkydmhoaHE2bzJxb2R6OTB2dGhjZGp0MHAzeTVsYjd2byZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/sZAVdCHy1rKY8/giphy.gif",
    wartortle: "https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExeGl1MDJycThsN2N3bWNuOHpzMzl3ZjE4ZjlxdmUxdnFlNXJ5YW9ldyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/JYfQy6aDhezb65mpPU/giphy.gif",
    charmander: "https://media.tenor.com/jwHkGGFNoH8AAAAi/shiny-charmander-pokemon.gif",
    charizard: "https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExdHNkaXpzZWg5dmkxZzUyNm9uZzZieGIwMjh5aWUzc2VmdXc5aGd4NSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/LM1dM95kwccNJWkovq/giphy.gif",
    squirtle: "https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExeDd2dmdud3EwdmUxOGZmazh5ODVmMjJ2cmtoZXFteXo2czA1b3ljNyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/dTWgGXLigmTl2f8Dm3/giphy.gif",
    blastoise: "https://media.tenor.com/Mx7NYmMM2wIAAAAi/blastoise-pokemon-pokemon.gif",
    metapod: "https://media.tenor.com/XU4umWE120UAAAAi/metapod-pokemon.gif",
    butterfree: "https://media.tenor.com/mH-ITcFV4JcAAAAi/butterfree-cute.gif",
    kakuna: "https://media.tenor.com/AwISvCKVT4EAAAAi/%D7%A4%D7%95%D7%A7%D7%99%D7%9E%D7%95%D7%9F.gif",
    pidgey: "https://media.tenor.com/-CMi8j6QnEYAAAAi/shiny-pidgeotto-anime.gif",
    pidgeot: "https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExZTM5cHV2MHRmanoyOGc3OTkxOWU3OGNwYmY0Mm1ycDAzaWZsZ3lqaCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/Ctdo2F6D4dZBnXyB7A/giphy.gif",
    pidgeotto: "https://media.tenor.com/YaKArTnL7EgAAAAi/pidgeotto.gif",
    beedrill: "https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExZnBleWh2cW05c3YzZTM2N3h2dzE5djJqcWF0NHN0cnppZGJyNzNjZSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/r5n9cc79bBLkc0zMau/giphy.gif",
    rattata: "https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExNWI2dzdva2d2NjhzOTQzMGdvZDAwcHA0cTNlbmNheGI4emo4NjR2bCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/M966FaGEfPqtOAHROo/giphy.gif",
    raticate: "https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExazNjaGJnYXl0enI1OXB4NXY3dGVzOW1peTNvcGRzNWQ4emJhNTU0cyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/mEhrrOHohttOmLpE3s/giphy.gif",
    spearow: "https://media.tenor.com/u35TAQS6bPgAAAAi/shiny-spearow-spearow.gif",
    arbok: "https://media.tenor.com/zAsjXr_Zy-4AAAAi/arbok-poison-type.gif",
    fearow: "https://media.tenor.com/TCRzm66NCSMAAAAi/shiny-fearow-fearow.gif",
    ekans: "https://media.tenor.com/X-tXMMmztqwAAAAi/shiny-ekans-ekans.gif",
    pikachu: "https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExMnJkamwwYjVsdmlydXhlMnBjMjVwZjJnZmF1c2VnZTlob293b3R0OCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/FRDFK0bgXdAic/giphy.gif",
    raichu: "https://media.tenor.com/SbCYyNZXhhcAAAAi/raichu-happy.gif",
  };